# Data Mining - Lab - 2

#  Numpy  &  Perform Data Exploration with Pandas
<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Data Mining</b></center>
<center><b><h1>Lab - 2</b></center>  
<center><b><h1>Nidhi Makasana </b></center> 
 <center><b><h1>23031701030</b></center> 
     <center><b><h1>05/06/2025</b></center> 
<pre>

-------------------------------------------------------------------------------
## Numpy

1) NumPy (Numerical Python) is a powerful open-source library in Python used for numerical and scientific computing.<br>
2) It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them efficiently.<br>
3) NumPy is highly optimized and written in C, making it much faster than using regular Python lists for numerical operations.<br>
4) It serves as the foundation for many other Python libraries in data science and machine learning, like pandas, TensorFlow, and scikit-learn.<br>
5) With features like broadcasting, vectorization, and integration with C/C++ code, NumPy allows for cleaner and faster code in numerical computations.<br>



### Step 1. Import the Numpy library

In [7]:
import numpy as np



### Step 2. Create a 1D array of numbers

In [5]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr1=np.arange(10,20)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
arr2=np.array([10,20,30,40,50,60,70,80,90])
arr2

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

### Step 3. Reshape 1D to 2D Array

In [19]:
arr3=np.arange(20).reshape(5,4)
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### Step 4. Create a Linspace array

In [21]:
# not specified number generate 50 default
arr4=np.linspace(10,15)
arr4

array([10.        , 10.10204082, 10.20408163, 10.30612245, 10.40816327,
       10.51020408, 10.6122449 , 10.71428571, 10.81632653, 10.91836735,
       11.02040816, 11.12244898, 11.2244898 , 11.32653061, 11.42857143,
       11.53061224, 11.63265306, 11.73469388, 11.83673469, 11.93877551,
       12.04081633, 12.14285714, 12.24489796, 12.34693878, 12.44897959,
       12.55102041, 12.65306122, 12.75510204, 12.85714286, 12.95918367,
       13.06122449, 13.16326531, 13.26530612, 13.36734694, 13.46938776,
       13.57142857, 13.67346939, 13.7755102 , 13.87755102, 13.97959184,
       14.08163265, 14.18367347, 14.28571429, 14.3877551 , 14.48979592,
       14.59183673, 14.69387755, 14.79591837, 14.89795918, 15.        ])

In [23]:
#value decare that number give
arr4=np.linspace(10,15,10)
arr4

array([10.        , 10.55555556, 11.11111111, 11.66666667, 12.22222222,
       12.77777778, 13.33333333, 13.88888889, 14.44444444, 15.        ])

### Step 5. Create a Random Numbered Array

In [31]:
# 1D
arr5=np.random.rand(6)
arr5

array([0.22941467, 0.14214213, 0.34946733, 0.03002088, 0.42161409,
       0.81843342])

In [9]:
# 2D
arr5=np.random.rand(6,4)
arr5

array([[0.60246629, 0.81715577, 0.28107111, 0.81606815],
       [0.15280955, 0.10801099, 0.6553912 , 0.31251527],
       [0.5479626 , 0.00589336, 0.77219676, 0.90335022],
       [0.70232721, 0.85161593, 0.58942292, 0.8191587 ],
       [0.57234442, 0.9916849 , 0.23797232, 0.47956904],
       [0.09254834, 0.42345929, 0.13661631, 0.56023866]])

### Step 6. Create a Random Integer Array

In [60]:
arr6=np.random.randint(4,10)
arr6

9

In [54]:
# range first value,sec value,size
arr6=np.random.randint(4,10,size =3)
arr6

array([7, 4, 6])

In [58]:
arr6=np.random.randint(10,30,size =(4,5))
arr6

array([[17, 15, 14, 11, 17],
       [18, 16, 27, 22, 13],
       [19, 13, 16, 20, 12],
       [21, 20, 14, 26, 11]])

### Step 7. Create a 1D Array and get Max,Min,ArgMax,ArgMin

In [13]:
arr7=np.random.randint(10,30,10)
arr7

array([13, 20, 12, 13, 21, 25, 19, 13, 27, 19])

In [23]:
arr7.max()

27

In [25]:
arr7.min()

12

In [27]:
arr7.argmax()

8

In [29]:
arr7.argmin()

2

### Step 8. Indexing in 1D Array

In [161]:
arr8=np.random.randint(10,20,8)
arr8

array([18, 12, 17, 15, 12, 14, 15, 19])

In [155]:
arr8[4]

18

In [163]:
arr8[2:4]

array([17, 15])

### Step 9. Indexing in 2D Array

In [31]:
arr9=np.random.randint(10,30,size=(4,4))
arr9

array([[16, 18, 19, 29],
       [20, 22, 15, 20],
       [13, 26, 22, 20],
       [13, 24, 12, 21]])

In [35]:
arr9[1,1]

22

In [39]:
arr9[1][3]

20

In [167]:
arr9.dtype
print(type(arr9))

<class 'numpy.ndarray'>


In [41]:
arr9[3]

array([13, 24, 12, 21])

In [43]:
#specific column 
arr9[:,3]

array([29, 20, 20, 21])

In [45]:
# row multiple
arr9[0:3]

array([[16, 18, 19, 29],
       [20, 22, 15, 20],
       [13, 26, 22, 20]])

In [47]:
#sepific element
arr9[1][2]

15

### Step 10. Conditional Selection

In [57]:
arr10=np.random.randint(20,40,20)
arr10

array([29, 22, 29, 21, 34, 33, 39, 32, 22, 38, 33, 20, 39, 32, 27, 35, 35,
       30, 22, 22])

In [59]:
# (true and false ans)
arr10 >25
# arr10[arr10>25]

array([ True, False,  True, False,  True,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
       False, False])

In [227]:
arr10[(arr10>30) & (arr10<35)]

array([33, 33, 31, 34, 33, 31, 31])

### 🔥You did it! 10 exercises down — you're on fire! 🔥

## Pandas



### Step 1. Import the necessary libraries

In [69]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user). 

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [71]:
users=pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user" ,sep="|",index_col="user_id")
users

age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

### Step 4. See the first 25 entries

In [73]:
users.head(25)

age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

### Step 5. See the last 10 entries

In [253]:
users.tail(10)

age gender     occupation zip_code
user_id                                    
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

### Step 6. What is the number of observations in the dataset?

In [75]:
users.shape[0]

943

### Step 7. What is the number of columns in the dataset?

In [261]:
users.shape[1]

4

### Step 8. Print the name of all the columns.

In [265]:
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

In [269]:
users.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

### Step 10. What is the data type of each column?

In [77]:
users.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### Step 11. Print only the occupation column

In [79]:
users['occupation']

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...      
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

### Step 12. How many different occupations are in this dataset?

In [81]:
users.occupation.unique()

array(['technician', 'other', 'writer', 'executive', 'administrator',
       'student', 'lawyer', 'educator', 'scientist', 'entertainment',
       'programmer', 'librarian', 'homemaker', 'artist', 'engineer',
       'marketing', 'none', 'healthcare', 'retired', 'salesman', 'doctor'],
      dtype=object)

In [283]:
users.occupation.nunique()

21

### Step 13. What is the most frequent occupation?

In [83]:
# users['occupation'].value_counts().head(1)
users['occupation'].value_counts().head(1)

occupation
student    196
Name: count, dtype: int64

In [85]:
users['occupation'].value_counts().idxmax()

'student'

### Step 14. Summarize the DataFrame.

In [307]:
users.describe()

age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

### Step 15. Summarize all the columns

In [313]:
users.describe(include="all")

age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [315]:
users['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

In [321]:
users['age'].mean()

34.05196182396607

### Step 18. What is the age with least occurrence?

In [329]:
users['age'].value_counts().tail()

age
7     1
66    1
11    1
10    1
73    1
Name: count, dtype: int64

### You're not just learning, you're mastering it. Keep aiming higher! 🚀